# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CopyCoordsToIfh
                                 A QGIS plugin
 Copy coordinates to an ifh importable format
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-14
        copyright            : (C) 2019 by Jonas VL
        email                : jonasvl_qgis@outlook.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CopyCoordsToIfh class from file CopyCoordsToIfh.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .copy_coords_to_ifh import CopyCoordsToIfh
    return CopyCoordsToIfh(iface)
