# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ExportAttributesToExcel
                                 A QGIS plugin
 Exports the attribute values of pre-defined layers to a pre-defined excel file.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-14
        copyright            : (C) 2019 by Jonas Van Loocke
        email                : jonasvl_qgis@outlook.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ExportAttributesToExcel class from file ExportAttributesToExcel.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .export_attributes_to_excel import ExportAttributesToExcel
    return ExportAttributesToExcel(iface)
